from __future__ import annotations

import re

DEFAULT_ROLES = ("pm", "arch", "prod", "dev", "qa", "ops", "coord", "liaison")
DEFAULT_ROLE_SCOPES: dict[str, str] = {
    "coord": "internal routing + escalation triage",
    "liaison": "user communication + clarifications",
    "pm": "overall delivery / milestone planning",
}
FULL_NAME_RE = re.compile(r"^.+-[0-9]{8}-[0-9]{6}-[0-9]+$")
FULL_NAME_SPLIT_RE = re.compile(r"^(.+)-[0-9]{8}-[0-9]{6}-[0-9]+$")

MSG_SEQ_FILE = "message_seq.json"
MSG_ID_WIDTH = 6

INBOX_DIR = "inbox"
INBOX_UNREAD_DIR = "unread"
INBOX_READ_DIR = "read"
INBOX_OVERFLOW_DIR = "overflow"
INBOX_MAX_UNREAD_DEFAULT = 15

REQUESTS_DIR = "requests"
REQUEST_META_FILE = "meta.json"
REQUEST_RESPONSES_DIR = "responses"
REQUEST_STATUS_OPEN = "open"
REQUEST_STATUS_DONE = "done"
REQUEST_STATUS_TIMED_OUT = "timed_out"
REQUEST_TARGET_STATUS_PENDING = "pending"
REQUEST_TARGET_STATUS_REPLIED = "replied"
REQUEST_TARGET_STATUS_BLOCKED = "blocked"
REQUEST_DEADLINE_DEFAULT_S = 3600.0
REQUEST_BLOCK_SNOOZE_DEFAULT_S = 900.0  # 15 minutes

STATE_DIR = "state"
STATE_STATUS_WORKING = "working"
STATE_STATUS_DRAINING = "draining"
STATE_STATUS_IDLE = "idle"
STATE_STATUSES = {STATE_STATUS_WORKING, STATE_STATUS_DRAINING, STATE_STATUS_IDLE}

DRIVE_MODE_RUNNING = "running"
DRIVE_MODE_STANDBY = "standby"
DRIVE_MODES = {DRIVE_MODE_RUNNING, DRIVE_MODE_STANDBY}

STATE_INBOX_CHECK_INTERVAL_DEFAULT = 60.0
STATE_IDLE_WAKE_DELAY_DEFAULT = 60.0
STATE_WATCH_INTERVAL_DEFAULT = 60.0
STATE_ACTIVITY_WINDOW_DEFAULT = 120.0
STATE_ACTIVE_GRACE_PERIOD_DEFAULT = 180.0
STATE_ACTIVITY_CAPTURE_LINES_DEFAULT = 200
STATE_AUTO_ENTER_ENABLED_DEFAULT = True
STATE_AUTO_ENTER_COOLDOWN_DEFAULT = 30.0
STATE_AUTO_ENTER_TAIL_WINDOW_LINES_DEFAULT = 80
STATE_AUTO_ENTER_PATTERNS_DEFAULT = ("3. No, and tell Codex what to do differently (esc)",)
DRIVE_MODE_DEFAULT = DRIVE_MODE_RUNNING
DRIVE_DRIVER_ROLE_DEFAULT = "coord"
DRIVE_BACKUP_ROLE_DEFAULT = "pm"
DRIVE_COOLDOWN_DEFAULT = 600.0
DRIVE_UNIT_ROLE_DEFAULT = "admin"
DRIVE_SUBTREE_STATE_FILE = "drive_subtrees.json"
DRIVE_SUBTREE_STATUS_ACTIVE = "active"
DRIVE_SUBTREE_STATUS_STOPPED = "stopped"
DRIVE_SUBTREE_STATUSES = {DRIVE_SUBTREE_STATUS_ACTIVE, DRIVE_SUBTREE_STATUS_STOPPED}
STATE_WORKING_STALE_THRESHOLD_DEFAULT = 180.0
STATE_WORKING_ALERT_COOLDOWN_DEFAULT = 600.0
STATE_WAKE_MESSAGE_DEFAULT = (
    "INBOX wake: you have unread messages. Run: bash .codex/skills/ai-team-workflow/scripts/atwf inbox"
)
STATE_REPLY_WAKE_MESSAGE_DEFAULT = (
    "REPLY wake: you have pending reply-needed. Run: bash .codex/skills/ai-team-workflow/scripts/atwf reply-needed"
)

# Back-compat aliases (single-file atwf.py used these names).
_MSG_SEQ_FILE = MSG_SEQ_FILE
_MSG_ID_WIDTH = MSG_ID_WIDTH

_INBOX_DIR = INBOX_DIR
_INBOX_UNREAD_DIR = INBOX_UNREAD_DIR
_INBOX_READ_DIR = INBOX_READ_DIR
_INBOX_OVERFLOW_DIR = INBOX_OVERFLOW_DIR
_INBOX_MAX_UNREAD_DEFAULT = INBOX_MAX_UNREAD_DEFAULT

_REQUESTS_DIR = REQUESTS_DIR
_REQUEST_META_FILE = REQUEST_META_FILE
_REQUEST_RESPONSES_DIR = REQUEST_RESPONSES_DIR
_REQUEST_STATUS_OPEN = REQUEST_STATUS_OPEN
_REQUEST_STATUS_DONE = REQUEST_STATUS_DONE
_REQUEST_STATUS_TIMED_OUT = REQUEST_STATUS_TIMED_OUT
_REQUEST_TARGET_STATUS_PENDING = REQUEST_TARGET_STATUS_PENDING
_REQUEST_TARGET_STATUS_REPLIED = REQUEST_TARGET_STATUS_REPLIED
_REQUEST_TARGET_STATUS_BLOCKED = REQUEST_TARGET_STATUS_BLOCKED
_REQUEST_DEADLINE_DEFAULT_S = REQUEST_DEADLINE_DEFAULT_S
_REQUEST_BLOCK_SNOOZE_DEFAULT_S = REQUEST_BLOCK_SNOOZE_DEFAULT_S

_STATE_DIR = STATE_DIR
_STATE_STATUS_WORKING = STATE_STATUS_WORKING
_STATE_STATUS_DRAINING = STATE_STATUS_DRAINING
_STATE_STATUS_IDLE = STATE_STATUS_IDLE
_STATE_STATUSES = STATE_STATUSES

_DRIVE_MODE_RUNNING = DRIVE_MODE_RUNNING
_DRIVE_MODE_STANDBY = DRIVE_MODE_STANDBY
_DRIVE_MODES = DRIVE_MODES

_STATE_INBOX_CHECK_INTERVAL_DEFAULT = STATE_INBOX_CHECK_INTERVAL_DEFAULT
_STATE_IDLE_WAKE_DELAY_DEFAULT = STATE_IDLE_WAKE_DELAY_DEFAULT
_STATE_WATCH_INTERVAL_DEFAULT = STATE_WATCH_INTERVAL_DEFAULT
_STATE_ACTIVITY_WINDOW_DEFAULT = STATE_ACTIVITY_WINDOW_DEFAULT
_STATE_ACTIVE_GRACE_PERIOD_DEFAULT = STATE_ACTIVE_GRACE_PERIOD_DEFAULT
_STATE_ACTIVITY_CAPTURE_LINES_DEFAULT = STATE_ACTIVITY_CAPTURE_LINES_DEFAULT
_STATE_AUTO_ENTER_ENABLED_DEFAULT = STATE_AUTO_ENTER_ENABLED_DEFAULT
_STATE_AUTO_ENTER_COOLDOWN_DEFAULT = STATE_AUTO_ENTER_COOLDOWN_DEFAULT
_STATE_AUTO_ENTER_TAIL_WINDOW_LINES_DEFAULT = STATE_AUTO_ENTER_TAIL_WINDOW_LINES_DEFAULT
_STATE_AUTO_ENTER_PATTERNS_DEFAULT = STATE_AUTO_ENTER_PATTERNS_DEFAULT

_DRIVE_MODE_DEFAULT = DRIVE_MODE_DEFAULT
_DRIVE_DRIVER_ROLE_DEFAULT = DRIVE_DRIVER_ROLE_DEFAULT
_DRIVE_BACKUP_ROLE_DEFAULT = DRIVE_BACKUP_ROLE_DEFAULT
_DRIVE_COOLDOWN_DEFAULT = DRIVE_COOLDOWN_DEFAULT
_DRIVE_UNIT_ROLE_DEFAULT = DRIVE_UNIT_ROLE_DEFAULT
_DRIVE_SUBTREE_STATE_FILE = DRIVE_SUBTREE_STATE_FILE
_DRIVE_SUBTREE_STATUS_ACTIVE = DRIVE_SUBTREE_STATUS_ACTIVE
_DRIVE_SUBTREE_STATUS_STOPPED = DRIVE_SUBTREE_STATUS_STOPPED
_DRIVE_SUBTREE_STATUSES = DRIVE_SUBTREE_STATUSES

_STATE_WORKING_STALE_THRESHOLD_DEFAULT = STATE_WORKING_STALE_THRESHOLD_DEFAULT
_STATE_WORKING_ALERT_COOLDOWN_DEFAULT = STATE_WORKING_ALERT_COOLDOWN_DEFAULT
_STATE_WAKE_MESSAGE_DEFAULT = STATE_WAKE_MESSAGE_DEFAULT
_STATE_REPLY_WAKE_MESSAGE_DEFAULT = STATE_REPLY_WAKE_MESSAGE_DEFAULT
